---
title: "Intro part II"
output: html_notebook
---

# Introdution

Bouleversement stat -> science des données. Crise stat. (data science in a box)

Evolution en pédagogie (how learning happens) et pédagogie à disctance forcée par COVID.

Science des données appliquée à la pédagogie (Data science in Education with R) guzman2019

<!-- Guyliann

Les cours de biostatistiques de l'Université de Mons du cursus en biologie sont complètement revue afin de proposer des cours de sciences des données biologiques. 

en classe inversée. Ces nouveaux cours intégrent des notions de biostastique ainsi que des notions sur la gestion de projet, la gestion de version, la recherche reproductible et l'open data.

L'approche en classe inversée permet de rendre les étudiants actif de leur apprentissage, ce qui a pour avantage d'améliorer les résultats des étudiants [@Freeman2014]. 

-->

The ability to analyze actual datasets is a critical knowledge to be developed in data science courses through practical sessions. Work is done in the University or at home. Access to suitable computer hardware and software. Different approaches, from software fully inline (RStudio Cloud, Chromebook data science) to solutions where the software is installed on the Student's computers. The later raises problems of license for proprietary software, but also installation and configuration issues. An intermediary solution that combines preinstallation/preconfiguration with availability of the software at home is to use a virtual machine, or a containerization system like docker. We use a preconfigured VirtualBox virtual machine wxith R, RStudio, Rmarkdown (Baumer2014), git, and a series of R packages preinstalled. This allows to play with the concepts and work on the various projects anywhere (in the computer lab, at home, uing a laptop, ...). To fix theoretical concepts through applied exercises is a key aspect of learning data science [@Larwin2011].  cetinkaya-rundel2017

The software environment chosen for the exercises and projects is also critical: using professional tools with the students in class allows to get used to the same tools that will bne used later on during the career. This was highlighted by [@Auker2020] for instance, for the analysis of ecological data.

Teaching data science in cursus that are far away from computing science, mathematics or statistics is further challenging because the students enter in a foreign world and have much more exotic concepts, techniques and tools to master. This generate anxiety (see for instance [@Onwuegbuzie2003], for students in biology) and learning has to be decomposed in smaller steps to avoid quick exposition to unknown concepts and tools. A student in computing science already masters probably one or more computing languages, has be acquainted with version control systems, database and the way data are represented in a computer. A student in mathematics or statistics is familiar with various concept that underpin the techniques to analyse the data. On the other hand, students in biology, medicine, psychology, social sciences, economics, etc. have very different *a priori* knowledges. 



