# Install all required R packages to run the analyses
# Copyright (c), 2021, Philippe Grosjean (phgrosjean@sciviews.org)
#
# Note: we used R version 4.0.5. Results may vary with a different version of R
# We also use SciViews::R, which is an opinionated subset of R packages and
# functions on top of base R and tidyverse <https://www.tidyverse.org>
install.packages("tidyverse", )
install.packages("glue")
install.packages("fs")
install.packages("data.table")
install.packages("purrr")
install.packages("kohonen")
install.packages("ellipse")
install.packages("cowplot")
install.packages("scales")
install.packages("latticeExtra")
install.packages("viridis")
install.packages("pryr")
install.packages("ggplotify")
install.packages("ggpubr")
install.packages("ggrepel")
install.packages("ggfortify")
install.packages("ggdendro")
install.packages("tsibble")
install.packages("Hmisc")
install.packages("proto")
install.packages("igraph")
install.packages("knitr")
install.packages("multcomp")
install.packages("iterators")
install.packages("vegan")
install.packages("factoextra")
install.packages("fastcluster")
install.packages("flashClust")
install.packages("ape")
install.packages("rstatix")
install.packages("remotes")
install.packages("svMisc")
remotes::install_github("SciViews/flow@1.0")
remotes::install_github("SciViews/data.io@1.2.2")
remotes::install_github("SciViews/chart@1.3")
remotes::install_github("SciViews/SciViews@1.1.1")
